import React, { useState, useEffect, useRef } from 'react';
import { Play, Pause, SkipForward, SkipBack, Volume2, Music, ListMusic, Monitor, Search, User, Disc, Maximize2, Minimize2, Plus, Trash2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:5000';

export default function App() {
    const [songs, setSongs] = useState([]);
    const [filteredSongs, setFilteredSongs] = useState([]);
    const [currentSong, setCurrentSong] = useState(null);
    const [isPlaying, setIsPlaying] = useState(false);
    const [currentTime, setCurrentTime] = useState(0);
    const [duration, setDuration] = useState(0);
    const [volume, setVolume] = useState(0.7);

    // Layout & UI State
    const [searchQuery, setSearchQuery] = useState('');
    const [currentView, setCurrentView] = useState('all');
    const [selectedArtist, setSelectedArtist] = useState(null);
    const [isTheaterMode, setIsTheaterMode] = useState(false);

    // Synchronized LRC Lyrics State
    const [isLyricsModeActive, setIsLyricsModeActive] = useState(false);
    const lyricsContainerRef = useRef(null);
    const [lyrics, setLyrics] = useState([]);
    const [currentLyricIndex, setCurrentLyricIndex] = useState(-1);

    // Persistent Playlist Engine State
    const [playlists, setPlaylists] = useState(() => {
        const saved = localStorage.getItem('scs_playlists');
        return saved ? JSON.parse(saved) : { 'My Favorites': [] };
    });
    const [selectedPlaylist, setSelectedPlaylist] = useState(null);
    const [newPlaylistName, setNewPlaylistName] = useState('');
    const [activeMenuSongId, setActiveMenuSongId] = useState(null);

    // Dynamic Bright & Saturated Color Palette State
    const [dominantColor, setDominantColor] = useState('rgb(59, 130, 246)');
    const [secondaryColor, setSecondaryColor] = useState('rgb(16, 185, 129)');

    // Refs for Audio Engine, Visualization, and Lyric Alignment
    const audioRef = useRef(null);
    const visualizerCanvasRef = useRef(null);
    const ambientCanvasRef = useRef(null);
    const audioContextRef = useRef(null);
    const analyserRef = useRef(null);
    const sourceRef = useRef(null);
    const lyricContainerRef = useRef(null);

    useEffect(() => {
        if (lyricContainerRef.current && currentLyricIndex !== -1) {
            const container = lyricContainerRef.current;
            // Find all lyric lines excluding the top padding element
            const lyricElements = container.querySelectorAll('div:not(.pointer-events-none)');
            const activeElement = lyricElements[currentLyricIndex];

            if (activeElement) {
                const containerHeight = container.clientHeight;
                const elementTop = activeElement.offsetTop;
                const elementHeight = activeElement.clientHeight;

                // Calculate the exact scroll target to position the active element in the middle
                const scrollToPosition = elementTop - (containerHeight / 2) + (elementHeight / 2);

                container.scrollTo({
                    top: scrollToPosition,
                    behavior: 'smooth'
                });
            }
        }
    }, [currentLyricIndex]);

    // Animation Frame Trackers
    const visualizerFrameRef = useRef(null);
    const ambientFrameRef = useRef(null);

    // Synchronize Playlists with localStorage on change
    useEffect(() => {
        localStorage.setItem('scs_playlists', JSON.stringify(playlists));
    }, [playlists]);

    // Fetch Index Library Assets
    useEffect(() => {
        fetch(`${BACKEND_URL}/api/songs`)
            .then((res) => res.json())
            .then((data) => {
                const { songs, autoPlaylists } = data;

                if (songs && Array.isArray(songs)) {
                    setSongs(songs);
                    setFilteredSongs(songs);
                    if (songs.length > 0) setCurrentSong(songs[0]);

                    // 🔄 FIXED BASE64 MIGRATION ENGINE
                    setPlaylists((prevPlaylists) => {
                        // Read directly from the accurate storage key layout
                        const savedRaw = localStorage.getItem('scs_playlists');
                        let migrated = savedRaw ? JSON.parse(savedRaw) : { ...prevPlaylists };

                        Object.keys(migrated).forEach((name) => {
                            // Skip folder-based system playlists generated by backend
                            if (autoPlaylists && autoPlaylists[name]) return;

                            migrated[name] = migrated[name].map((trackRef) => {
                                if (!trackRef) return trackRef;

                                // If it's already a long absolute path ID token, it's already migrated
                                if (trackRef.length > 100 && !trackRef.includes('.mp3')) {
                                    return trackRef;
                                }

                                let decodedFilename = trackRef;

                                // Try decoding the token from your old base64 filename format
                                try {
                                    // Safe URL-Base64 to normal conversion if necessary
                                    const normalBase64 = trackRef.replace(/-/g, '+').replace(/_/g, '/');
                                    const decoded = atob(normalBase64);
                                    if (decoded.toLowerCase().endsWith('.mp3') || decoded.toLowerCase().endsWith('.m4a') || decoded.toLowerCase().endsWith('.flac')) {
                                        decodedFilename = decoded;
                                    }
                                } catch (e) {
                                    // Not base64 encoded text, treat as raw filename fallback
                                }

                                // Match the filename string against the new absolute path song profiles
                                const matchedTrack = songs.find(
                                    s => s.filename.trim().toLowerCase() === decodedFilename.trim().toLowerCase()
                                );

                                // Return the new path-safe ID token, or drop back to original reference
                                return matchedTrack ? matchedTrack.id : trackRef;
                            });
                        });

                        // Combine your updated user tracks with the backend folder-playlists
                        const finalPlaylists = {
                            ...migrated,
                            ...autoPlaylists
                        };

                        // Commit changes back to the precise local storage index
                        localStorage.setItem('scs_playlists', JSON.stringify(migrated));

                        return finalPlaylists;
                    });
                }
            })
            .catch((err) => console.error('Library connection error:', err));
    }, []);

    // Filter Pipeline Engine
    useEffect(() => {
        let result = [...songs];
        if (searchQuery.trim() !== '') {
            const query = searchQuery.toLowerCase();
            result = result.filter(s =>
                s.title.toLowerCase().includes(query) ||
                s.artist.toLowerCase().includes(query)
            );
        }
        if (currentView === 'artists' && selectedArtist) {
            result = result.filter(s => s.artist === selectedArtist);
        } else if (currentView === 'playlists' && selectedPlaylist) {
            result = result.filter(s => (playlists[selectedPlaylist] || []).includes(s.id));
        }
        setFilteredSongs(result);
    }, [searchQuery, currentView, selectedArtist, selectedPlaylist, songs, playlists]);

    // Fetch and Parse Synchronized LRC Document
    useEffect(() => {
        if (!currentSong || !currentSong.id) return; // FIXED: Protect against uninitialized ID tokens

        // Reset old lyrics immediately to avoid showing previous song lines
        setLyrics([]);
        setCurrentLyricIndex(-1);

        // If backend scan confirmed this track has no paired .lrc file, skip request
        if (currentSong.hasLyrics === false) {
            setLyrics([{ time: 0, text: "Instrumental or missing LRC file mapping" }]);
            return;
        }

        // FIXED: Query using currentSong.id instead of filename
        fetch(`${BACKEND_URL}/api/lyrics/${currentSong.id}`)
            .then(res => {
                if (!res.ok) throw new Error('No lyric document asset located');
                return res.json();
            })
            .then(data => {
                if (data.lyrics) {
                    parseLrcLyrics(data.lyrics);
                }
            })
            .catch(() => {
                setLyrics([{ time: 0, text: "Instrumental or missing LRC file mapping" }]);
            });
    }, [currentSong?.id]); // FIXED: Dependency listens directly to the track's safe unique ID

    // Helper: Core LRC Format Processing Engine (Fixed for 2-digit decimals)
    const parseLrcLyrics = (rawLrcText) => {
        const lines = rawLrcText.split('\n');
        const parsedEntries = [];

        // Updated regex to catch standard 2-digit or 3-digit ms decimals (\d+)
        const lrcRegex = /\[(\d+):(\d+)\.(\d+)\](.*)/;

        lines.forEach(line => {
            const cleanLine = line.trim();
            const match = lrcRegex.exec(cleanLine);

            if (match) {
                const minutes = parseInt(match[1], 10);
                const seconds = parseInt(match[2], 10);
                const msRaw = match[3];
                const lyricString = match[4].trim();

                // Convert the raw decimal segment to actual fractions of a second
                // e.g., ".51" becomes 0.51 seconds, ".5" becomes 0.50 seconds
                const millisecondsFloat = parseFloat(`0.${msRaw}`);
                const dynamicTotalSeconds = minutes * 60 + seconds + millisecondsFloat;

                // Only append lines that contain actual text content
                if (lyricString) {
                    parsedEntries.push({ time: dynamicTotalSeconds, text: lyricString });
                }
            }
        });

        // Sort chronologically
        parsedEntries.sort((a, b) => a.time - b.time);

        if (parsedEntries.length > 0) {
            setLyrics(parsedEntries);
        } else {
            setLyrics([{ time: 0, text: "LRC file found, but could not parse timestamps." }]);
        }
    };

    // Sync Playback Engine State
    useEffect(() => {
        if (!audioRef.current) return;
        if (isPlaying) {
            audioRef.current.play().catch(() => setIsPlaying(false));
            setupAudioEngine();
        } else {
            audioRef.current.pause();
        }
    }, [isPlaying, currentSong]);

    useEffect(() => {
        if (audioRef.current) audioRef.current.volume = volume;
    }, [volume]);

    // Track Time Progression to Sync Highlights & Scrolling
    const handleTimeUpdate = () => {
        if (!audioRef.current) return;
        const time = audioRef.current.currentTime;
        setCurrentTime(time);

        // Pinpoint current active lyric line position
        if (lyrics.length > 0) {
            let targetIndex = -1;
            for (let i = 0; i < lyrics.length; i++) {
                if (time >= lyrics[i].time) {
                    targetIndex = i;
                } else {
                    break;
                }
            }
            if (targetIndex !== currentLyricIndex) {
                setCurrentLyricIndex(targetIndex);
            }
        }
    };

    // Center the active lyric line
    useEffect(() => {
        if (currentLyricIndex !== -1 && lyricsContainerRef.current) {
            const activeElement = lyricsContainerRef.current.children[currentLyricIndex];
            if (activeElement) {
                activeElement.scrollIntoView({
                    behavior: 'smooth',
                    block: 'center' // Keeps the current line perfectly centered on screen
                });
            }
        }
    }, [currentLyricIndex, isLyricsModeActive]);

    // Close menus on outside click handlers
    useEffect(() => {
        const handleOutsideClick = () => setActiveMenuSongId(null);
        window.addEventListener('click', handleOutsideClick);
        return () => window.removeEventListener('click', handleOutsideClick);
    }, []);

    useEffect(() => {
        if (!currentSong) return;

        const extractSmartColors = async () => {
            const artUrl = `${BACKEND_URL}/api/artwork/${currentSong.id}`;
            const img = new Image();
            img.crossOrigin = "Anonymous";
            img.src = artUrl;

            img.onload = () => {
                const canvas = document.createElement('canvas');
                const ctx = canvas.getContext('2d');
                canvas.width = 50; // Higher resolution scan for better variety
                canvas.height = 50;
                ctx.drawImage(img, 0, 0, 50, 50);

                const pxData = ctx.getImageData(0, 0, 50, 50).data;
                const threshold = 80; // Minimum brightness (R+G+B average > threshold)

                let foundDominant = null;
                let foundSecondary = null;

                // Helper: Check if pixel is "bright enough"
                const isBright = (r, g, b) => (r + g + b) / 3 > threshold;

                // Iterate through pixels (step by 4 to skip every few pixels for performance)
                for (let i = 0; i < pxData.length; i += 16) {
                    const r = pxData[i], g = pxData[i + 1], b = pxData[i + 2];

                    if (isBright(r, g, b)) {
                        if (!foundDominant) {
                            foundDominant = { r, g, b };
                        } else if (Math.abs(r - foundDominant.r) > 50) {
                            // Ensure secondary color is distinct from dominant
                            foundSecondary = { r, g, b };
                            break; // We found two distinct bright colors, stop scanning
                        }
                    }
                }

                // Fallback if we didn't find bright enough colors
                const finalDom = foundDominant || { r: 59, g: 130, b: 246 };
                const finalSec = foundSecondary || { r: 29, g: 78, b: 216 };

                setDominantColor(`rgb(${finalDom.r}, ${finalDom.g}, ${finalDom.b})`);
                setSecondaryColor(`rgb(${finalSec.r}, ${finalSec.g}, ${finalSec.b})`);
            };
        };

        extractSmartColors();
    }, [currentSong?.id]);

    const setupAudioEngine = () => {
        if (!audioRef.current) return;

        if (!audioContextRef.current) {
            const AudioContextClass = window.AudioContext || window.webkitAudioContext;
            audioContextRef.current = new AudioContextClass();

            analyserRef.current = audioContextRef.current.createAnalyser();
            analyserRef.current.fftSize = 256;

            sourceRef.current = audioContextRef.current.createMediaElementSource(audioRef.current);
            sourceRef.current.connect(analyserRef.current);
            analyserRef.current.connect(audioContextRef.current.destination);
        }

        triggerVisualizerLoop();
        triggerAmbientBackgroundLoop();
    };

    // --- UPGRADED: NEON CURVED AUDIO FINS VISUALIZER ENGINE ---
    const triggerVisualizerLoop = () => {
        if (!visualizerCanvasRef.current || !analyserRef.current) return;

        const canvas = visualizerCanvasRef.current;
        const ctx = canvas.getContext('2d');
        const analyser = analyserRef.current;
        const bufferLength = analyser.frequencyBinCount;
        const dataArray = new Uint8Array(bufferLength);

        const drawVisualizer = () => {
            if (!isPlaying || !isTheaterMode) return;
            visualizerFrameRef.current = requestAnimationFrame(drawVisualizer);

            analyser.getByteFrequencyData(dataArray);

            const dpr = window.devicePixelRatio || 1;
            const rect = canvas.getBoundingClientRect();
            if (canvas.width !== rect.width * dpr) {
                canvas.width = rect.width * dpr;
                canvas.height = rect.height * dpr;
                ctx.scale(dpr, dpr);
            }

            ctx.clearRect(0, 0, rect.width, rect.height);

            const centerX = rect.width / 2;
            // CAVA typically uses fewer, chunkier bars for that "solid" feel
            const activeBarsPool = 60;
            const barWidth = (rect.width / 2 / activeBarsPool) * 0.8;
            const gap = 4;

            // Dynamic gradient for the rectangles
            const grad = ctx.createLinearGradient(0, rect.height, 0, 0);
            grad.addColorStop(0, dominantColor || '#3b82f6');
            grad.addColorStop(1, secondaryColor || '#8b5cf6');

            ctx.fillStyle = grad;

            for (let i = 0; i < activeBarsPool; i++) {
                // Pick a frequency sample (mapping buffer to active bars)
                const index = Math.floor((i / activeBarsPool) * (bufferLength * 0.5));
                const percent = dataArray[index] / 255;
                const barHeight = Math.pow(percent, 1.5) * rect.height * 0.8;

                if (barHeight < 2) continue;

                ctx.fillRect(centerX + (i * (barWidth + gap)), rect.height - barHeight, barWidth, barHeight);

                ctx.fillRect(centerX - (i * (barWidth + gap)) - barWidth, rect.height - barHeight, barWidth, barHeight);
            }
        };

        if (visualizerFrameRef.current) cancelAnimationFrame(visualizerFrameRef.current);
        drawVisualizer();
    };

    const triggerAmbientBackgroundLoop = () => {
        if (!ambientCanvasRef.current || !analyserRef.current) return;

        const canvas = ambientCanvasRef.current;
        const ctx = canvas.getContext('2d');
        const analyser = analyserRef.current;
        const bufferLength = analyser.frequencyBinCount;
        const dataArray = new Uint8Array(bufferLength);

        const particleCount = 45;
        const particles = [];

        for (let i = 0; i < particleCount; i++) {
            particles.push({
                x: Math.random() * window.innerWidth,
                y: Math.random() * window.innerHeight,
                baseRadius: Math.random() * 20 + 10,
                speedX: (Math.random() - 0.5) * 0.4,
                speedY: (Math.random() - 0.5) * 0.4,
                alpha: Math.random() * 0.2 + 0.05,
                colorSeed: Math.random() > 0.5
            });
        }

        const drawAmbient = () => {
            if (!isPlaying) return;
            ambientFrameRef.current = requestAnimationFrame(drawAmbient);

            analyser.getByteFrequencyData(dataArray);

            let lowFrequencies = 0;
            let highFrequencies = 0;
            for (let i = 0; i < 15; i++) lowFrequencies += dataArray[i];
            for (let i = 80; i < 110; i++) highFrequencies += dataArray[i];

            const bassFactor = (lowFrequencies / 15) / 255;
            const trebleFactor = (highFrequencies / 30) / 255;

            const dpr = window.devicePixelRatio || 1;
            canvas.width = window.innerWidth * dpr;
            canvas.height = window.innerHeight * dpr;
            ctx.scale(dpr, dpr);

            ctx.clearRect(0, 0, window.innerWidth, window.innerHeight);

            particles.forEach(p => {
                p.x += p.speedX * (1 + bassFactor * 4);
                p.y += p.speedY * (1 + trebleFactor * 4);

                if (p.x < -50) p.x = window.innerWidth + 50;
                if (p.x > window.innerWidth + 50) p.x = -50;
                if (p.y < -50) p.y = window.innerHeight + 50;
                if (p.y > window.innerHeight + 50) p.y = -50;

                const targetRadius = p.baseRadius * (1 + (p.colorSeed ? bassFactor * 0.8 : trebleFactor * 1.2));

                ctx.beginPath();
                const grad = ctx.createRadialGradient(p.x, p.y, 0, p.x, p.y, targetRadius);
                const coreColor = p.colorSeed ? dominantColor : secondaryColor;

                const cleanRGB = coreColor.replace('rgb', 'rgba').replace(')', '');

                grad.addColorStop(0, `${cleanRGB}, ${p.alpha * (1 + bassFactor)})`);
                grad.addColorStop(0.6, `${cleanRGB}, ${p.alpha * 0.3})`);
                grad.addColorStop(1, 'rgba(0,0,0,0)');

                ctx.fillStyle = grad;
                ctx.arc(p.x, p.y, targetRadius, 0, Math.PI * 2);
                ctx.fill();
            });
        };

        if (ambientFrameRef.current) cancelAnimationFrame(ambientFrameRef.current);
        drawAmbient();
    };

    useEffect(() => {
        if (isPlaying) {
            setTimeout(() => {
                triggerVisualizerLoop();
                triggerAmbientBackgroundLoop();
            }, 80);
        }
        return () => {
            if (visualizerFrameRef.current) cancelAnimationFrame(visualizerFrameRef.current);
            if (ambientFrameRef.current) cancelAnimationFrame(ambientFrameRef.current);
        };
    }, [isTheaterMode, dominantColor, secondaryColor, isPlaying]);

    const createPlaylist = (e) => {
        e.preventDefault();
        const name = newPlaylistName.trim();
        if (!name || playlists[name]) return;
        setPlaylists({ ...playlists, [name]: [] });
        setSelectedPlaylist(name);
        setCurrentView('playlists');
        setNewPlaylistName('');
    };

    const deletePlaylist = (name, e) => {
        e.stopPropagation();
        const updated = { ...playlists };
        delete updated[name];
        setPlaylists(updated);
        if (selectedPlaylist === name) {
            setCurrentView('all');
            setSelectedPlaylist(null);
        }
    };

    const toggleSongInPlaylist = (playlistName, songId, e) => {
        e.stopPropagation();
        const currentList = playlists[playlistName] || [];
        let updatedList = currentList.includes(songId)
            ? currentList.filter(id => id !== songId)
            : [...currentList, songId];
        setPlaylists({ ...playlists, [playlistName]: updatedList });
        setActiveMenuSongId(null);
    };

    const uniqueArtists = [...new Set(songs.map((s) => s.artist))];
    const handlePlayPause = () => setIsPlaying(!isPlaying);
    const playSong = (song) => { setCurrentSong(song); setIsPlaying(true); };
    const handleLoadedMetadata = () => setDuration(audioRef.current.duration);

    const handleSeek = (e) => {
        const time = parseFloat(e.target.value);
        audioRef.current.currentTime = time;
        setCurrentTime(time);
    };

    const skipTrack = (direction) => {
        const activeList = filteredSongs.length > 0 ? filteredSongs : songs;
        const index = activeList.findIndex((s) => s.id === currentSong?.id);
        if (index === -1) return;
        let nextIndex = direction === 'next' ? index + 1 : index - 1;
        if (nextIndex >= activeList.length) nextIndex = 0;
        if (nextIndex < 0) nextIndex = activeList.length - 1;
        playSong(activeList[nextIndex]);
    };

    const formatTime = (time) => {
        if (isNaN(time)) return '0:00';
        const min = Math.floor(time / 60);
        const sec = Math.floor(time % 60);
        return `${min}:${sec < 10 ? '0' : ''}${sec}`;
    };

    return (
        <div className="flex flex-col h-screen w-screen overflow-hidden bg-[#030509] text-gray-100 font-sans select-none relative">

            <canvas ref={ambientCanvasRef} className="absolute inset-0 w-full h-full pointer-events-none z-0" />

            <div
                className="absolute inset-0 pointer-events-none overflow-hidden z-10 opacity-25 blur-[160px] transition-all duration-1000"
                style={{ background: `radial-gradient(circle at 50% 50%, ${dominantColor} 0%, ${secondaryColor} 45%, transparent 100%)` }}
            />

            {/* TOP COMPONENT REGION BLOCK */}
            <div className="flex flex-1 overflow-hidden relative z-20 min-h-0">

                {/* Sidebar - Smoothly collapses on mobile/tablet to give the grid space */}
                <aside className="hidden lg:flex flex-col w-64 bg-black/30 backdrop-blur-xl border-r border-white/5 p-5 overflow-y-auto shrink-0">
                    <div className="flex items-center gap-3 mb-8">
                        <div className="p-2.5 rounded-xl shadow-lg transition-colors duration-1000" style={{ backgroundColor: dominantColor }}>
                            <Music className="w-5 h-5 text-white" />
                        </div>
                        <span className="font-bold text-lg tracking-tight bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent">SCS PLAYER</span>
                    </div>

                    <div className="space-y-6">
                        <div>
                            <p className="px-4 text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Discover</p>
                            <nav className="space-y-1">
                                <button onClick={() => { setCurrentView('all'); setSelectedArtist(null); setSelectedPlaylist(null); }} className={`flex items-center gap-3 w-full px-4 py-2.5 text-sm font-medium rounded-xl transition-all ${currentView === 'all' ? 'bg-white/5 text-white' : 'text-gray-400 hover:text-white'}`}>
                                    <ListMusic className="w-4 h-4" /> All Tracks
                                </button>
                                <button onClick={() => { setCurrentView('artists'); if (uniqueArtists.length > 0 && !selectedArtist) setSelectedArtist(uniqueArtists[0]); }} className={`flex items-center gap-3 w-full px-4 py-2.5 text-sm font-medium rounded-xl transition-all ${currentView === 'artists' ? 'bg-white/5 text-white' : 'text-gray-400 hover:text-white'}`}>
                                    <User className="w-4 h-4" /> Artists
                                </button>
                            </nav>
                        </div>

                        <div>
                            <p className="px-4 text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">My Playlists</p>
                            <form onSubmit={createPlaylist} className="flex gap-2 mb-3 px-2">
                                <input type="text" placeholder="Create playlist..." value={newPlaylistName} onChange={(e) => setNewPlaylistName(e.target.value)} className="bg-white/5 border border-white/10 rounded-lg px-2.5 py-1.5 text-xs focus:outline-none focus:border-blue-500 w-full text-white" />
                                <button type="submit" className="p-1.5 bg-blue-600 hover:bg-blue-500 rounded-lg text-white transition"><Plus className="w-4 h-4" /></button>
                            </form>

                            <nav className="space-y-1 max-h-[280px] overflow-y-auto pr-1">
                                {Object.keys(playlists).map(name => (
                                    <button key={name} onClick={() => { setCurrentView('playlists'); setSelectedPlaylist(name); }} className={`flex items-center justify-between group w-full px-4 py-2 text-sm font-medium rounded-xl transition-all ${currentView === 'playlists' && selectedPlaylist === name ? 'bg-white/5 text-white' : 'text-gray-400 hover:text-white hover:bg-white/[0.02]'}`}>
                                        <span className="truncate">✨ {name}</span>
                                        <div className="flex items-center gap-2 flex-shrink-0">
                                            <span className="text-[10px] bg-white/10 px-1.5 py-0.5 rounded-md text-gray-300">{playlists[name].length}</span>
                                            {name !== 'My Favorites' && (
                                                <Trash2 onClick={(e) => deletePlaylist(name, e)} className="w-3.5 h-3.5 text-gray-500 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity" />
                                            )}
                                        </div>
                                    </button>
                                ))}
                            </nav>
                        </div>
                    </div>

                    <div className="mt-auto p-4 bg-white/[0.02] border border-white/5 rounded-xl text-xs text-gray-400 flex items-center gap-2">
                        <Monitor className="w-4 h-4 text-emerald-400 animate-pulse" /> Local Storage Engine Active
                    </div>
                </aside>

                {/* Workspace Container */}
                <main className="flex-1 overflow-y-auto p-4 sm:p-6 md:p-8 pb-24 min-w-0">

                    {(currentView === 'playlists' || currentView === 'all' || currentView === 'artists') && (
                        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 md:mb-8">
                            <div>
                                <h1 className="text-xl sm:text-2xl font-extrabold tracking-tight md:text-3xl capitalize bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent truncate max-w-xs sm:max-w-none">
                                    {currentView === 'all' && "Your Music Repository"}
                                    {currentView === 'playlists' && selectedPlaylist}
                                    {currentView === 'artists' && `${selectedArtist || 'Artists'}`}
                                </h1>
                            </div>
                            <div className="relative w-full sm:w-72 md:w-80">
                                <Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" />
                                <input
                                    type="text"
                                    placeholder="Search tracks..."
                                    value={searchQuery}
                                    onChange={(e) => setSearchQuery(e.target.value)}
                                    className="w-full bg-white/5 border border-white/10 rounded-xl pl-10 pr-4 py-2 text-sm focus:outline-none focus:border-white/20 transition-all text-white"
                                />
                            </div>
                        </div>
                    )}

                    {currentView === 'playlists' && selectedPlaylist && (
                        <motion.div
                            initial={{ opacity: 0, y: -10 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="p-4 sm:p-6 rounded-2xl border border-white/5 mb-6 md:mb-8 flex flex-col sm:flex-row items-start sm:items-center gap-4 sm:gap-5 relative overflow-hidden bg-white/[0.01]"
                        >
                            <div className="w-14 h-14 sm:w-16 sm:h-16 rounded-xl flex items-center justify-center bg-gradient-to-br from-white/10 to-white/0 border border-white/10 text-white shadow-inner shrink-0">
                                <ListMusic className="w-7 h-7 sm:w-8 sm:h-8" style={{ color: dominantColor }} />
                            </div>
                            <div className="min-w-0 flex-1">
                                <span className="text-[10px] tracking-widest font-bold uppercase text-blue-400">PLAYLIST</span>
                                <h1 className="text-xl sm:text-2xl font-black text-white md:text-3xl tracking-tight truncate">{selectedPlaylist}</h1>
                                <div className="flex items-center gap-4 text-xs text-gray-400 mt-1 font-medium">
                                    <span className="flex items-center gap-1"><Music className="w-3.5 h-3.5" /> {(playlists[selectedPlaylist] || []).length} tracks</span>
                                </div>
                            </div>
                            {(playlists[selectedPlaylist] || []).length > 0 && (
                                <button
                                    onClick={() => playSong(songs.find(s => playlists[selectedPlaylist].includes(s.id)))}
                                    className="w-full sm:w-auto sm:ml-auto px-5 py-2.5 rounded-xl bg-white text-black text-xs sm:text-sm font-bold shadow-lg hover:scale-105 active:scale-95 transition whitespace-nowrap"
                                >
                                    Play Collection
                                </button>
                            )}
                        </motion.div>
                    )}

                    {currentView === 'artists' && (
                        <div className="flex gap-2 overflow-x-auto pb-4 mb-6 border-b border-white/5 scrollbar-none">
                            {uniqueArtists.map(artist => (
                                <button key={artist} onClick={() => setSelectedArtist(artist)} className={`px-4 py-1.5 rounded-full text-xs font-medium whitespace-nowrap transition-all ${selectedArtist === artist ? 'bg-white text-black font-semibold' : 'bg-white/5 text-gray-400 hover:text-white'}`}>
                                    {artist}
                                </button>
                            ))}
                        </div>
                    )}

                    {filteredSongs.length === 0 ? (
                        <div className="text-center py-16 sm:py-20 border border-dashed border-white/10 rounded-2xl bg-white/[0.005]">
                            <ListMusic className="w-10 h-10 mx-auto text-gray-600 mb-3" />
                            <h3 className="text-sm font-semibold text-gray-400">No tracks found here</h3>
                            <p className="text-xs text-gray-500 mt-1">Try adding tracks or modifying your active filters.</p>
                        </div>
                    ) : (
                        /* Highly responsive fluid grid system using smart minmax widths */
                        <div className="grid grid-cols-[repeat(auto-fill,minmax(140px,1fr))] sm:grid-cols-[repeat(auto-fill,minmax(180px,1fr))] gap-4 sm:gap-5">
                            {filteredSongs.map((song) => {
                                const isThisPlaying = currentSong?.id === song.id;
                                return (
                                    <div key={song.id} onClick={() => playSong(song)} className={`group p-3 sm:p-4 rounded-2xl cursor-pointer transition-all duration-300 border relative backdrop-blur-sm min-w-0 ${isThisPlaying ? 'bg-white/5 border-white/20 shadow-lg shadow-black/40' : 'bg-white/[0.01] border-white/5 hover:bg-white/[0.04]'}`}>

                                        <div className="absolute top-5 right-5 sm:top-6 sm:right-6 z-30 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <button
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    setActiveMenuSongId(activeMenuSongId === song.id ? null : song.id);
                                                }}
                                                className="p-1.5 bg-black/70 hover:bg-black text-white border border-white/10 rounded-lg backdrop-blur-md transition shadow"
                                            >
                                                <Plus className="w-3.5 h-3.5" />
                                            </button>

                                            <AnimatePresence>
                                                {activeMenuSongId === song.id && (
                                                    <motion.div
                                                        initial={{ opacity: 0, scale: 0.95, y: 5 }}
                                                        animate={{ opacity: 1, scale: 1, y: 0 }}
                                                        exit={{ opacity: 0, scale: 0.95, y: 5 }}
                                                        className="absolute right-0 mt-1 w-44 sm:w-48 bg-[#0a0d14] border border-white/10 rounded-xl shadow-2xl p-1.5 z-50 text-left"
                                                        onClick={(e) => e.stopPropagation()}
                                                    >
                                                        <p className="text-[10px] font-bold text-gray-500 px-2 py-1 uppercase tracking-wider border-b border-white/5 mb-1">Add to Playlist</p>
                                                        <div className="max-h-32 sm:max-h-40 overflow-y-auto space-y-0.5">
                                                            {Object.keys(playlists).map(name => {
                                                                const isAdded = playlists[name].includes(song.id);
                                                                return (
                                                                    <button
                                                                        key={name}
                                                                        onClick={(e) => toggleSongInPlaylist(name, song.id, e)}
                                                                        className="w-full text-left px-2.5 py-1.5 text-xs rounded-lg transition text-gray-300 hover:bg-white/5 flex items-center justify-between"
                                                                    >
                                                                        <span className="truncate">{name}</span>
                                                                        {isAdded && <span className="text-[10px] font-bold text-emerald-400 shrink-0 ml-1">✓ Added</span>}
                                                                    </button>
                                                                );
                                                            })}
                                                        </div>
                                                    </motion.div>
                                                )}
                                            </AnimatePresence>
                                        </div>

                                        <div className="relative aspect-square w-full rounded-xl overflow-hidden bg-gray-900 mb-2 sm:mb-3 border border-white/5">
                                            <img
                                                src={`${BACKEND_URL}/api/artwork/${song.id}`}
                                                alt=""
                                                className="w-full h-full object-cover"
                                                onError={(e) => { e.target.src = 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=300'; }}
                                            />
                                            <div className={`absolute inset-0 bg-black/50 flex items-center justify-center transition-opacity ${isThisPlaying ? 'opacity-100' : 'opacity-0 group-hover:opacity-100'}`}>
                                                <div className="p-2.5 sm:p-3 bg-white text-black rounded-full shadow-lg scale-90 group-hover:scale-100 transition-transform">
                                                    {isThisPlaying && isPlaying ? <Pause className="w-3.5 h-3.5 sm:w-4 sm:h-4 fill-current" /> : <Play className="w-3.5 h-3.5 sm:w-4 sm:h-4 fill-current ml-0.5" />}
                                                </div>
                                            </div>
                                        </div>
                                        <h3 className="font-semibold text-xs sm:text-sm truncate text-gray-100 pr-4">{song.title}</h3>
                                        <p className="text-[11px] sm:text-xs text-gray-400 truncate mt-0.5">{song.artist}</p>
                                    </div>
                                );
                            })}
                        </div>
                    )}
                </main>
            </div>

            {/* BOTTOM SEPARATE CONTROLLER DOCK ELEMENT */}
            <motion.footer
                onDoubleClick={() => setIsTheaterMode(!isTheaterMode)}
                animate={{
                    height: isTheaterMode ? '100vh' : 'auto',
                    position: isTheaterMode ? 'absolute' : 'relative'
                }}
                transition={{ type: 'spring', damping: 26, stiffness: 130 }}
                className="left-0 right-0 bottom-0 bg-black/60 backdrop-blur-3xl border-t border-white/5 z-50 overflow-hidden flex-shrink-0"
            >
                {!isTheaterMode ? (
                    <div className="px-4 sm:px-6 py-3 sm:py-4 flex flex-row items-center justify-between gap-4">
                        {/* Track Info Section */}
                        <div className="flex items-center gap-3 w-1/3 sm:w-1/4 min-w-0">
                            {currentSong && (
                                <>
                                    <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-lg overflow-hidden bg-gray-900 flex-shrink-0 border border-white/10 hidden xs:block">
                                        <img
                                            src={`${BACKEND_URL}/api/artwork/${currentSong.id}`}
                                            alt=""
                                            className="w-full h-full object-cover"
                                            onError={(e) => { e.target.src = 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=100'; }}
                                        />
                                    </div>
                                    <div className="min-w-0">
                                        <h4 className="text-xs sm:text-sm font-semibold truncate text-white">{currentSong.title}</h4>
                                        <p className="text-[11px] sm:text-xs text-gray-400 truncate">{currentSong.artist}</p>
                                    </div>
                                </>
                            )}
                        </div>

                        {/* Controls & Progress bar */}
                        <div className="flex flex-col items-center gap-1.5 flex-1 max-w-xl min-w-0">
                            <div className="flex items-center gap-4 sm:gap-6">
                                <button onClick={(e) => { e.stopPropagation(); skipTrack('prev'); }} className="text-gray-400 hover:text-white transition"><SkipBack className="w-4 h-4 fill-current" /></button>
                                <button onClick={(e) => { e.stopPropagation(); handlePlayPause(); }} className="p-2 bg-white text-black rounded-full hover:scale-105 active:scale-95 transition shadow">
                                    {isPlaying ? <Pause className="w-4 h-4 fill-current" /> : <Play className="w-4 h-4 fill-current ml-0.5" />}
                                </button>
                                <button onClick={(e) => { e.stopPropagation(); skipTrack('next'); }} className="text-gray-400 hover:text-white transition"><SkipForward className="w-4 h-4 fill-current" /></button>
                            </div>
                            <div className="w-full flex items-center gap-2 sm:gap-3 text-[10px] text-gray-400">
                                <span className="tabular-nums">{formatTime(currentTime)}</span>
                                <input type="range" min="0" max={duration || 0} value={currentTime} onClick={(e) => e.stopPropagation()} onChange={handleSeek} className="w-full h-1 bg-white/10 rounded-lg appearance-none cursor-pointer accent-blue-500 min-w-0" />
                                <span className="tabular-nums">{formatTime(duration)}</span>
                            </div>
                        </div>

                        {/* Action Panel */}
                        <div className="flex items-center justify-end gap-4 w-auto sm:w-1/4">
                            <button onClick={() => setIsTheaterMode(true)} className="text-gray-400 hover:text-white transition p-1"><Maximize2 className="w-4 h-4" /></button>
                        </div>
                    </div>
                ) : (
                    /* CINEMATIC THEATER CANVAS MATRIX ENV */
                    <div className="w-full h-full flex flex-col justify-between relative p-4 sm:p-5 md:p-6 bg-black/40 overflow-y-auto lg:overflow-hidden">

                        {/* Ambient Fin Vector Layer */}
                        <div className="absolute inset-x-0 bottom-0 top-2/6 pointer-events-none z-10 px-4 md:px-12 hidden md:block">
                            <canvas ref={visualizerCanvasRef} className="w-full h-full opacity-80" />
                        </div>

                        {/* Top Status Bar */}
                        <div className="flex justify-between items-center w-full max-w-6xl mx-auto z-20 mb-4 lg:mb-0">
                            <div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-widest transition-colors duration-1000" style={{ color: secondaryColor }}>
                                <Disc className="w-3.5 h-3.5 animate-spin [animation-duration:6s]" /> Kinetic Audio Environment
                            </div>
                            <button onClick={() => setIsTheaterMode(false)} className="flex items-center gap-2 bg-white/5 border border-white/10 px-3 py-1.5 rounded-xl text-xs hover:bg-white/10 text-white transition backdrop-blur-md">
                                <Minimize2 className="w-3.5 h-3.5" /> Collapse Workspace
                            </button>
                        </div>

                        {/* Split Theater View Layout - Balanced 5-to-7 column ratio for better lyric streaming space */}
                        <div className="grid grid-cols-1 lg:grid-cols-12 items-center justify-center gap-6 md:gap-8 lg:gap-10 max-w-6xl w-full mx-auto my-auto z-20 min-h-0">

                            {/* Left Column: Premium Expanded Cover Details */}
                            <div className="lg:col-span-5 flex flex-col items-center lg:items-start text-center lg:text-left justify-center w-full min-w-0">
                                {currentSong && (
                                    <div
                                        className="relative w-40 h-40 sm:w-52 sm:h-52 md:w-60 md:h-60 xl:w-80 xl:h-80 rounded-xl md:rounded-2xl overflow-hidden border border-white/10 flex-shrink-0 transition-all duration-500 bg-gray-900 shadow-black/90 mb-4 md:mb-6"
                                        style={{ boxShadow: `0 20px 45px -15px ${dominantColor}40` }}
                                    >
                                        <img
                                            src={`${BACKEND_URL}/api/artwork/${currentSong.id}`}
                                            alt=""
                                            className="w-full h-full object-cover"
                                            onError={(e) => { e.target.src = 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=600'; }}
                                        />
                                    </div>
                                )}

                                {currentSong && (
                                    <div className="w-full px-1">
                                        <h2 className="text-lg sm:text-xl md:text-2xl xl:text-4xl font-black tracking-tight text-white line-clamp-1 leading-snug w-full drop-shadow-md">{currentSong.title}</h2>
                                        <p className="text-xs sm:text-sm md:text-base font-medium mt-0.5 md:mt-1 transition-colors duration-1000 drop-shadow-sm w-full" style={{ color: secondaryColor }}>{currentSong.artist}</p>
                                    </div>
                                )}

                                {/* Timeline Slider Section */}
                                <div className="mt-3 md:mt-5 w-full max-w-sm mx-auto lg:mx-0 px-1">
                                    <input type="range" min="0" max={duration || 0} value={currentTime} onChange={handleSeek} className="w-full h-1 bg-white/10 rounded-lg appearance-none cursor-pointer accent-blue-500" />
                                    <div className="w-full flex justify-between items-center text-[11px] text-gray-400 mt-1.5 font-medium tabular-nums">
                                        <span>{formatTime(currentTime)}</span>
                                        <span>{formatTime(duration)}</span>
                                    </div>
                                </div>

                                {/* Deck Controls */}
                                <div className="flex items-center justify-center lg:justify-start gap-4 mt-4 w-full">
                                    <button onClick={() => skipTrack('prev')} className="text-gray-400 hover:text-white transition"><SkipBack className="w-4 h-4 fill-current" /></button>
                                    <button onClick={handlePlayPause} className="p-3 bg-white text-black rounded-full hover:scale-105 active:scale-95 transition shadow-lg">
                                        {isPlaying ? <Pause className="w-4 h-4 fill-current" /> : <Play className="w-4 h-4 fill-current ml-0.5" />}
                                    </button>
                                    <button onClick={() => skipTrack('next')} className="text-gray-400 hover:text-white transition"><SkipForward className="w-4 h-4 fill-current" /></button>

                                    <div className="items-center gap-2 ml-3 hidden sm:flex border border-white/5 bg-black/20 backdrop-blur-md px-3 py-1.5 rounded-xl">
                                        <Volume2 className="w-3.5 h-3.5 text-gray-400" />
                                        <input type="range" min="0" max="1" step="0.01" value={volume} onChange={(e) => setVolume(parseFloat(e.target.value))} className="w-12 h-1 bg-white/10 rounded-lg appearance-none accent-blue-500" />
                                    </div>
                                </div>
                            </div>

                            {/* Right Column: Clean Panoramic Lyrics Stream (Slightly wider for better tracking readability) */}
                            <div className="lg:col-span-7 w-full h-[240px] sm:h-[300px] lg:h-[380px] xl:h-[440px] relative flex flex-col rounded-xl md:rounded-2xl bg-black/15 backdrop-blur-md border border-white/5 p-4 mb-4 lg:mb-0">
                                <div
                                    ref={lyricContainerRef}
                                    className="flex-1 overflow-y-auto pr-1 space-y-3 md:space-y-4 font-medium text-center lg:text-left scroll-smooth min-h-0 select-text selection:bg-white/20 scrollbar-none"
                                >
                                    {/* Top padding to center first line */}
                                    <div className="h-[40%] flex-shrink-0 pointer-events-none" />

                                    {lyrics.map((line, index) => {
                                        const isActive = index === currentLyricIndex;
                                        return (
                                            <motion.div
                                                key={index}
                                                animate={{
                                                    scale: isActive ? 1.02 : 1.0,
                                                    opacity: isActive ? 1.0 : 0.3
                                                }}
                                                transition={{ duration: 0.22 }}
                                                className={`py-0.5 px-2 text-sm sm:text-lg md:text-xl xl:text-2xl rounded-lg transition-all origin-center lg:origin-left cursor-pointer ${isActive ? 'font-black text-white' : 'text-gray-300 font-semibold hover:opacity-70'}`}
                                                style={{ textShadow: isActive ? `0 0 20px ${dominantColor}50` : 'none' }}
                                                onClick={() => {
                                                    audioRef.current.currentTime = line.time;
                                                    setCurrentTime(line.time);
                                                }}
                                            >
                                                {line.text}
                                            </motion.div>
                                        );
                                    })}

                                    {/* Bottom padding to center last line */}
                                    <div className="h-[40%] flex-shrink-0 pointer-events-none" />
                                </div>
                            </div>

                        </div>
                        <div className="h-1 md:h-2 w-full flex-shrink-0"></div>
                    </div>
                )}
            </motion.footer>

            {currentSong && (
                <audio
                    ref={audioRef}
                    crossOrigin="anonymous"
                    src={`${BACKEND_URL}/api/stream/${currentSong.id}`} // Updated endpoint target parameter
                    onTimeUpdate={handleTimeUpdate}
                    onLoadedMetadata={handleLoadedMetadata}
                    onEnded={() => skipTrack('next')}
                />
            )}
        </div>
    );
}
